# Generated by Django 4.1.13 on 2024-05-27 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alumno',
            new_name='Alumnos',
        ),
    ]
