# Generated by Django 4.1.13 on 2024-05-27 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_rename_alumno_alumnos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alumnos',
            new_name='Alumno',
        ),
    ]
